### ISSUE TITLE
High-Fidelity Screen updaten

### ISSUE THREAD

**Issue by hurbeana** [hurbeana/mrtrash#6]
# Task List
- [x] Entscheiden welcher Screen aus dem Mockup in High-Fidelity umgesetzt werden muss
- [x] High fidelity mockup in Illustrator gestalten
- [ ] Mockup in Konzept Dokument updaten

# Beschreibung
Wir müssen einen High-Fidelity Screen umsetzen, weil der derzeitige Nichts-Aussagend ist. Bevor das gemacht wird, müssen wir #3 und #4 erledigen
